// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function DetectInstalls() {
  return window['go']['main']['App']['DetectInstalls']();
}

export function FetchNews(arg1) {
  return window['go']['main']['App']['FetchNews'](arg1);
}

export function GetBranding() {
  return window['go']['main']['App']['GetBranding']();
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function HandleDroppedPaths(arg1) {
  return window['go']['main']['App']['HandleDroppedPaths'](arg1);
}

export function Play(arg1) {
  return window['go']['main']['App']['Play'](arg1);
}

export function SyncServer(arg1, arg2) {
  return window['go']['main']['App']['SyncServer'](arg1, arg2);
}

export function ValidateInstall(arg1) {
  return window['go']['main']['App']['ValidateInstall'](arg1);
}
