// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CreateProfile(arg1:string,arg2:string):Promise<main.ProfileDTO>;

export function DetectInstalls():Promise<Array<main.DetectedInstall>>;

export function GetBranding():Promise<main.BrandingDTO>;

export function GetProfile(arg1:string):Promise<main.ProfileDTO>;

export function GetServers():Promise<Array<config.Server>>;

export function Play(arg1:string):Promise<void>;

export function SyncServer(arg1:string,arg2:boolean):Promise<void>;

export function ValidateInstall(arg1:string):Promise<main.DetectedInstall>;
